# Generated by Django 5.2.8 on 2026-01-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa produktu')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('category', models.CharField(choices=[('SH', 'Szampon'), ('CO', 'Odżywka'), ('MA', 'Maska'), ('OI', 'Olejek'), ('LI', 'Odżywka bez spłukiwania'), ('SE', 'Serum / kuracja')], max_length=2, verbose_name='Kategoria')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('suitable_porosity', models.CharField(blank=True, choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], help_text='Opcjonalnie – jeśli produkt jest szczególnie polecany dla danego typu porowatości.', max_length=4, verbose_name='Dla jakiej porowatości')),
                ('suitable_curl_type', models.CharField(blank=True, choices=[('1', 'Proste'), ('2', 'Falowane'), ('3', 'Kręcone'), ('4', 'Afro')], max_length=1, verbose_name='Dla jakiego typu skrętu')),
                ('is_featured', models.BooleanField(default=False, help_text='Jeśli zaznaczone – może się pojawiać w sekcji podpowiedzi pielęgnacyjnej.', verbose_name='Polecany produkt')),
                ('shop_url', models.URLField(blank=True, help_text='Jeśli macie docelowo sklep – tu można dodać link do zakupu.', verbose_name='Link do sklepu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produkt do włosów',
                'verbose_name_plural': 'Produkty do włosów',
            },
        ),
        migrations.CreateModel(
            name='HairTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł porady')),
                ('content', models.TextField(verbose_name='Treść porady')),
                ('porowatosc', models.CharField(blank=True, choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], help_text='Zostaw puste, jeśli porada jest ogólna.', max_length=4, verbose_name='Porowatość docelowa')),
                ('skret', models.CharField(blank=True, choices=[('1', 'Proste'), ('2', 'Falowane'), ('3', 'Kręcone'), ('4', 'Afro')], max_length=1, verbose_name='Typ skrętu docelowy')),
                ('dlugosc', models.CharField(blank=True, choices=[('S', 'Krótkie'), ('M', 'Średnie'), ('L', 'Długie')], max_length=1, verbose_name='Długość włosów docelowa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Porada pielęgnacyjna',
                'verbose_name_plural': 'Porady pielęgnacyjne',
            },
        ),
        migrations.CreateModel(
            name='HairProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inna')], default='I', max_length=1, verbose_name='Płeć')),
                ('porowatosc', models.CharField(choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], default='Med', max_length=4, verbose_name='Porowatość')),
                ('dlugosc', models.CharField(choices=[('S', 'Krótkie'), ('M', 'Średnie'), ('L', 'Długie')], default='M', max_length=1, verbose_name='Długość włosów')),
                ('skret', models.CharField(choices=[('1', 'Proste'), ('2', 'Falowane'), ('3', 'Kręcone'), ('4', 'Afro')], default='1', max_length=1, verbose_name='Typ skrętu')),
                ('tluszczenie', models.BooleanField(default=False, verbose_name='Przetłuszczająca się skóra głowy')),
                ('farba', models.BooleanField(default=False, verbose_name='Czy włosy są farbowane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Konto użytkownika powiązane z tym profilem włosów.', on_delete=django.db.models.deletion.CASCADE, related_name='hair_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil włosów',
                'verbose_name_plural': 'Profile włosów',
            },
        ),
        migrations.CreateModel(
            name='HairRoutineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data pielęgnacji')),
                ('care_type', models.CharField(choices=[('WASH', 'Mycie'), ('COND', 'Odżywka'), ('MASK', 'Maska'), ('OIL', 'Olejowanie'), ('SCALP', 'Pielęgnacja skóry głowy'), ('STYLE', 'Stylizacja')], max_length=6, verbose_name='Rodzaj pielęgnacji')),
                ('notes', models.TextField(blank=True, help_text='Np. jak zareagowały włosy, co się sprawdziło, co nie.', verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_used', models.ManyToManyField(blank=True, related_name='used_in_routines', to='hair_app.hairproduct', verbose_name='Użyte produkty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wpis pielęgnacji',
                'verbose_name_plural': 'Wpisy pielęgnacji',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'care_type')},
            },
        ),
    ]
