# Generated by Django 5.2.8 on 2026-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairproduct',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone może się pojawiać w sekcji podpowiedzi pielęgnacyjnej.', verbose_name='Polecany produkt'),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='shop_url',
            field=models.URLField(blank=True, help_text='Jeśli macie docelowo sklep tu można dodać link do zakupu.', verbose_name='Link do sklepu'),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='suitable_porosity',
            field=models.CharField(blank=True, choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], help_text='Opcjonalnie jeśli produkt jest szczególnie polecany dla danego typu porowatości.', max_length=4, verbose_name='Dla jakiej porowatości'),
        ),
    ]
