# Generated by Django 5.2.8 on 2026-01-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0002_alter_hairproduct_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairproduct',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pojawienie sie w sekcji podpowiedzi pielęgnacji.', verbose_name='Polecany produkt'),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='shop_url',
            field=models.URLField(blank=True, help_text='Link do sklepu gdzie można kupić dany produkt.', verbose_name='Link do sklepu'),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='suitable_porosity',
            field=models.CharField(blank=True, choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], help_text='Co robi produkt dla tego typu porowatości.', max_length=4, verbose_name='Dla jakiej porowatości'),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='plec',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna'), ('O', 'Other')], default='O', max_length=1, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='hairtip',
            name='porowatosc',
            field=models.CharField(blank=True, choices=[('Low', 'Niskoporowate'), ('Med', 'Średnioporowate'), ('High', 'Wysokoporowate')], help_text='Zostaw puste, jeśli porada ogólna.', max_length=4, verbose_name='Porowatość docelowa'),
        ),
    ]
